---
dist: xenial
os: ["linux"]
language: node_js
node_js:
  - 14
  - 16
  - 18
cache: npm

install:
  - make deps

script:
  - make _test/ci || echo "Coverage probably insufficient!"
  - if [[ "$(node -v)" =~ "16." ]]; then npx coveralls < coverage/lcov.info; fi
