---
dist: xenial
os: ["linux"]
language: node_js
node_js:
  - 16
cache: npm

install:
  - make deps

script:
  - make _test/ci || echo "Coverage probably insufficient!"
  - npx coveralls < coverage/lcov.info
