---
name: ci

'on':
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  ci:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extras / Count Lines of Source Code
        run: cloc HEAD --exclude-dir=package-lock.json

      - name: Install requirements
        run: npm ci

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Build (and Deploy)
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      - name: Build (dev)
        if: github.ref == 'refs/heads/dev'
        run: npm run build:dev

      - name: Deploy (dev) [Copy static files over]
        if: github.ref == 'refs/heads/dev'
        run: rm -rf /var/www/app/* && mv build/* /var/www/app/

      - name: Build (prod)
        if: github.ref == 'refs/heads/prod'
        run: npm run build

      - name: Compress production build
        if: github.ref == 'refs/heads/prod'
        run: tar cJvf build-$(git rev-parse --short HEAD).tar.xz build/

      # Deploy (prod) [Upload artifacts]
      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/prod'
        with:
          path: build-*.tar.xz

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Lint
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - name: Lint
        run: npm run lint

      - name: Check
        run: npm run check
