---
name: ci

'on':
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  ci:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extras / Count Lines of Source Code
        run: cloc HEAD --exclude-dir=package-lock.json

      - name: Install requirements
        run: npm ci

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Deploy as long as it builds
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - name: Build (prod)
        if: github.ref == 'refs/heads/master'
        run: npm run build

      - name: Build (dev)
        if: github.ref == 'refs/heads/dev'
        run: npm run build:dev

      # TODO: how to copy over on prod?
      - name: Deploy (dev) [Copy static files over]
        if: github.ref == 'refs/heads/dev'
        run: rm -rf /var/www/app/* && mv build/* /var/www/app/

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Lint
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - name: Lint
        run: npm run lint

      - name: Check
        run: npm run check
