---
name: deploy-dev

"on":
  push:
    branches: ["dev"]

concurrency: dev

jobs:
  deploy-dev:
    runs-on: [self-hosted, dev-east]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extras / Count Lines of Source Code
        run: make extras/cloc

      - name: Clean up (from previous run)
        run: make clean purge

      - name: Install requirements
        run: make deps

      # NOTE: removing "CI=false" will cause warnings to be treated as errors
      - name: React Scripts (Build)
        run: CI=false make build

      - name: Copy static files over
        run: |
          rm -rf /var/www/react_app/*
          mv build/* /var/www/react_app/
