---
name: ci

'on':
  workflow_run:
    workflows: [ci]
    types:
      - completed

permissions:
  contents: read

jobs:
  ci:
    runs-on: [self-hosted, prod]
    steps:

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Download (and Deploy)
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      - name: Build (dev)
        if: github.ref == 'refs/heads/dev'
        run: npm run build:dev

      - name: Deploy (prod) [Copy static files over]
        if: github.ref == 'refs/heads/dev'
        run: rm -rf /var/www/app/* && mv build/* /var/www/app/
