---
name: deploy-dev

'on':
  push:
    branches:
      - '**'

concurrency: dev

jobs:
  deploy-dev:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extras / Count Lines of Source Code
        run: cloc HEAD

      - name: Install requirements
        run: npm i

      - name: Build
        run: npm run build

      - name: Copy static files over
        run: rm -rf /var/www/app/* && mv build/* /var/www/app/
