---
name: deploy-prod

"on":
  push:
    branches: ["prod"]

concurrency: prod

jobs:
  deploy-dev:
    runs-on: [self-hosted, vps76]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extras / Count Lines of Source Code
        run: make extras/cloc

      - name: Clean up (from previous run)
        run: make clean purge

      - name: Install requirements
        run: make deps

      - name: React Scripts (Build)
        run: make build

      - name: Copy static files over
        run: |
          rm -rf /var/www/react_app/*
          mv build/* /var/www/react_app/
