---
name: CI

"on":
  push: {}

jobs:
  test-linux:
    runs-on: ubuntu-latest
      with:
        node: 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        # use this to check for `cache-hit` ==>
        #  if: steps.npm-cache.outputs.cache-hit != 'true'
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install requirements
        run: make deps

      - name: Lint
        run: make lint

      - name: Test
        run: make _test/ci

      - name: Build
        run: make build

  # Windows integration tests: Makefile, Sanic lint/test
  test-win32:
    runs-on: windows-latest

    steps:
      - name: Configure Line Endings / git / LF
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        # use this to check for `cache-hit` ==>
        #  if: steps.npm-cache.outputs.cache-hit != 'true'
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install requirements
        run: make deps

      - name: Lint
        run: make lint

      # NOTE: win32 job only requires passing tests; no coverage enforcement
      - name: Test
        run: make _test/ci-no-cov
