---
name: test-linux

"on":
  push: {}

jobs:
  test-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      # NOTE: Linux job runs experimental NodeJS 18 & Ubuntu 22.04
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        # use this to check for `cache-hit` ==>
        #  if: steps.npm-cache.outputs.cache-hit != 'true'
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # NOTE: this is only performed on Linux
      - name: Install / "NPM License Checker"
        env:
          NPM_LICENSE_CHECKER_VERSION: 25.0.1
        run: npm i license-checker@$NPM_LICENSE_CHECKER_VERSION

      - name: Check Licenses
        env:
          APP_VERSION: 0.1.0
        run: "npx license-checker --production \
          --excludePackages 'nutra-web-v2@${{ env.APP_VERSION }}' \
          --onlyAllow \
          'MIT;\
          Apache-2.0;\
          ISC;\
          Python-2.0;\
          MPL-2.0;\
          Unlicense;\
          BSD-3-Clause;\
          BSD-2-Clause;\
          0BSD;\
          CC0-1.0;\
          CC-BY-4.0'
          "

      - name: Install requirements
        run: make deps

      - name: Lint
        run: make lint

      - name: Test
        run: |
          export CI=true
          export JEST_OPT_ARGS=
          make test

      # NOTE: build is only performed on Linux for now
      - name: Build
        run: make build
