---
name: test-linux

"on":
  push: {}

jobs:
  test-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      # NOTE: Linux job runs experimental NodeJS 18 & Ubuntu 22.04
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        # use this to check for `cache-hit` ==>
        #  if: steps.npm-cache.outputs.cache-hit != 'true'
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install requirements
        run: make deps

      - name: Lint
        run: make lint

      - name: Test
        run: |
          CI=true
          JEST_OPT_ARGS=
          make test

      # NOTE: build is only performed on Linux for now
      - name: Build
        run: make build
