---
name: test-win32

"on":
  push: {}

jobs:
  test-win32:
    runs-on: windows-latest

    steps:
      # NOTE: Windows has issues with line endings by default
      - name: Configure Line Endings / git / LF
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        # use this to check for `cache-hit` ==>
        #  if: steps.npm-cache.outputs.cache-hit != 'true'
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install requirements
        run: make deps

      - name: Lint
        run: make lint

      - name: Test
        run: >
          set CI=true
          set JEST_OPT_ARGS=
          make test
